Chandra/full airlock int
lablueprint/farm2people-web-app pull request #14
Opened 2021-02-16 08:53 UTC by curesh

Integrate persistence and local storage of important user metadeta. Also used cal blueprints[ auto schema generator](https://github.com/aivantg/airtable-schema-generator) to create airtable/ files which can be used to perform database API calls. 

Additionally, implemented rudimentary demonstration of access resolvers in [f2p server repo](https://github.com/lablueprint/farm2people-airlock-server). Can be expanded once user roles and desired access limitations are fleshed out.

Used redux for storing the user object and jwt token.

Also, reorganized repo to have centralized file for all authentication (and other) API calls.

2021-02-18 06:28 UTC, curesh commented
Also change the airtable.js file to use local host port 3000 to port 3001.

2021-02-18 07:06 UTC, ryanmtran requested changes
This is such a cool feature I'm so thankful for all the hard work you've put into this. My only comments would be some minor refactoring, removal of console logs, removal of unnecessary comments, passing down a function to functions like signupUser so we can set some state and just show an error message clientside if anything breaks, and other comments specified. If you can write some documentation in our notion to let other devs know how to setup everything (like the env file and generating the schemas) that would be so helpful! Thank you so much Chandra for taking up the mantle for this task. This is fantastic.

2021-02-18 07:06 UTC, ryanmtran commented on src/components/SignIn/SignInScreen.js
> +          console.log(records);
Make sure to remove console logs

2021-02-18 07:06 UTC, ryanmtran commented on src/components/SignIn/SignInScreen.js
> +          console.log(records);
You can also remove this Airtable request from line 21-26, because this was there for testing purposes

2021-02-18 07:06 UTC, ryanmtran commented on src/components/SignIn/SignInScreen.js
> +        setTimeout(() => { setLoading(false); }, 1000);
I think we can remove this setTimeout line now! Double check, but because of the await above, setLoading(false) is guaranteed to occur after the login function?

2021-02-18 07:06 UTC, ryanmtran commented on src/components/SignIn/SignInScreen.js
> +    if (store.getState().authenticated) {
WOOOOOO! Persistence this is amazing!

2021-02-18 07:06 UTC, ryanmtran commented on src/components/SignUp/SignUpForm.js
>        // TODO: Figure out if user, token variables need to persist
Is this TODO still relevant?

2021-02-18 07:06 UTC, ryanmtran commented on src/components/SignUp/SignUpForm.js
>        console.log("Error in signupuser func")
We can prolly setErrorMsg instead of doing a console.log and showcase it to the user or something

2021-02-18 07:06 UTC, ryanmtran commented on src/lib/airlock/airlock.js
> +// import { useState } from 'react';
Delete comment

2021-02-18 07:06 UTC, ryanmtran commented on src/lib/airlock/airlock.js
> +// import { toAirtableFormat } from '../airtable/airtable';
Delete comment

2021-02-18 07:06 UTC, ryanmtran commented on src/lib/airlock/airlock.js
> +    // TODO: Figure out if user, token variables need to persist
Question: What does this mean? Do we have to find a way to still persist the token?

2021-02-18 07:06 UTC, ryanmtran commented on src/lib/airlock/airlock.js
> +    console.log(res);
We can prolly delete this

2021-02-18 07:06 UTC, ryanmtran commented on src/lib/airlock/airlock.js
> +    console.log("Error in signupuser func")
Instead of these console logs, maybe we can pass the function setErrMsg down to this as an argument and set the state of the error message?

2021-02-18 07:06 UTC, ryanmtran commented on src/lib/airlock/airlock.js
> +      console.log(err);
Same as above

2021-02-18 07:06 UTC, ryanmtran commented on src/lib/airlock/airlock.js
> +    console.warn(err);
Same as above with setting error message state and passing that as a function to this

2021-02-18 07:06 UTC, ryanmtran commented on src/components/SignUp/SignUpForm.js
>  import Grid from '@material-ui/core/Grid';
I'm thinking we can rename this component from SignUpForm to SignUpScreen just for consistency

2021-03-07 00:38 UTC, curesh commented on src/lib/airlock/airlock.js
> +    // TODO: Figure out if user, token variables need to persist
Oh yeah those comments were from way before when I was still trying to figure out how to approach this feature. To answer your question, everything with regards to persistence is done!

2021-04-22 03:21 UTC, closed without merging