Marketplace sidebar
lablueprint/farm2people-web-app pull request #22
Opened 2021-04-13 07:42 UTC by hwang635

- Front end for the marketplace sidebar
- Full styling of side bar components: sort by dropdown menu, item/produce/farming season filter menus, filter by price menu
- Fixes to marketplace header + farm/produce card styling
- Still have several TODOs for airtable calls

2021-04-19 12:00 UTC, ryanmtran requested changes
Small nitpicks, question about implementation, and checking in with the design team. Also helen, you literally have one of the cleanest and elegant coding styles I've ever seen :O

This looks beautiful Helen. I can't wait to see this integrated.

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/FilterMenu.js
> +import '../../../assets/styles/fonts.css';
This is a great point about how we should prolly refactor the code moving forward.  For now though, master has fonts.css here in the directory structure, so can you change it to that and pull from master for next feature work?
<img width="164" alt="Screen Shot 2021-04-14 at 8 53 40 PM" src="https://user-images.githubusercontent.com/59102166/114811840-b2155e00-9d63-11eb-8ecf-9f6eb39212e4.png">

In the future we'll refactor to this way tho

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/FilterMenu.js
> +  const [isChecked, setIsChecked] = useState([0]); // -1 is checked, 1 is unchecked
Can you explain to me how the array is being initialized to represent all of the elements in filterOptions? I know you're using indexOf, but I don't see where isChecked gets expanded. And is there a reason why we use -1 and 1 instead of true and  false?

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/MarketplaceSidebar.js
> +import '../../../assets/styles/fonts.css';
Same as above for import

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/MarketplaceSidebar.js
> +      {/* Item type menu only shows for agency buyer view */}
This is an awesome comment

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/MarketplaceSidebar.js
> +      />
The way you implemented this is really elegant. I'm interested in how you will go about incorporating some type of prop to allow you to count for the total of a specific filterOption from Airtable

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/PriceMenu.js
> +import '../../../assets/styles/fonts.css';
Same as above

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/PriceMenu.js
> +  for (let i = 0; i < priceOptions.length - 1; i += 1) {
Let's try to stay away from for loops and use forEach or map

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/SortMenu.js
> +  const sortOptions = ['Best match', 'Expiration Date: latest first', 'Harvest Date: latest first', 'Best seller'];
You can pass sortOptions as a prop. Also for now, take out Harvest Date..., and Best Seller. (I will check in with you during work sesh bc we might replace Harvest Date with something else, remind me if I forget!)

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/MarketplaceScreen.js
> +                // key={TODO, no unique identifiers in table}
You can use the record id for this!

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/MarketplaceScreen.js
> +              // key={TODO, no unique identifiers in table}
You can use the record id for this!

2021-04-19 12:00 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/FilterMenu.js
> +          <Typography className={classes.resetText} onClick={resetFilters}>
For the reset, can we add some type of hover effect or button outline to convey to users that it is a component we interact with? We can ask Viv + design team how exactly we do that on Monday

2021-04-22 02:40 UTC, hwang635 commented on src/components/Marketplace/Sidebar/FilterMenu.js
> +  const [isChecked, setIsChecked] = useState([0]); // -1 is checked, 1 is unchecked
isChecked gets expanded into newChecked in the handleToggle fx, in this line: const newChecked = [...isChecked]; Then the if else statement modifies newChecked and isChecked is set to newChecked. I used -1 and 1 bc I based it off an example, I'll change it to true or false, that makes more sense.

2021-04-22 03:30 UTC, hwang635 commented on src/components/Marketplace/Sidebar/MarketplaceSidebar.js
> +      />
Thanks! To be honest I am also interested in how I will do that. I think my idea now is to have FilterMenu get each filterOption element and make a fx call to get the total inside that component.

2021-04-22 03:47 UTC, hwang635 commented on src/components/Marketplace/Sidebar/PriceMenu.js
> +  for (let i = 0; i < priceOptions.length - 1; i += 1) {
Ok! Is there a reason for loops < forEach/map?

2021-04-27 07:13 UTC, ryanmtran commented on src/components/Marketplace/Sidebar/PriceMenu.js
> +  for (let i = 0; i < priceOptions.length - 1; i += 1) {
Yeah! So forEach and map tends to be more connotative than a standard for loop

2021-04-27 07:28 UTC, ryanmtran approved these changes
Looks great to me! Thank you Helen for your work in this :)

2021-04-27 07:33 UTC, merged