InventoryManagerAirlock and FilterSidebar
lablueprint/farm2people-web-app pull request #40
Opened 2021-06-30 06:59 UTC by ElwynCruz

Changed the airtable calls to use the airlock stuff
Implemented the sidebar, using Helen's sidebar as a base
  - can filter listings by produce category, availability, sell by date, and price
  - can sort listings by various categories
  - pre-calculates the amount of listings that would be shown by each filter, and updates on adding/removing listings
  - can reset these filters with the reset button

2021-07-07 06:19 UTC, curesh commented
Try to make the sidebar a little wider if possible– some of the phrases are getting cut off ("Sell by date: ..." for example).

2021-07-07 06:21 UTC, curesh commented
For the filter by prices, if an invalid range is given ($4 to $1) could you display nothing? Currently, everything is displayed

2021-07-07 06:22 UTC, curesh commented
For the filter by prices, could you make the range inclusive? If there are produce cards for 2 dollars and ($2 to $2) is specified then the 2 dollar produces are shown?

2021-07-07 06:37 UTC, curesh commented on src/components/InventoryManager/InventoryManagerScreen.js
> +    const newFilter = [...filter];
Cool syntax– never seen it before!

2021-07-07 06:40 UTC, curesh commented on src/components/InventoryManager/InventoryManagerScreen.js
> +  useEffect(() => {
Would it be possible to combine the above two useEffects into a single hook?

2021-07-07 06:44 UTC, curesh commented on src/components/InventoryManager/InventoryManagerScreen.js
> +  filteredListings.sort((firstListing, secondListing) => (
Sorting feature doesn't seem to work on my end for some reason

2021-07-07 06:53 UTC, curesh commented on src/components/InventoryManager/Sidebar/InventoryManagerSidebar.js
> +        {/* TODO: Item type menu only shows for agency buyer view */}
Is this still a todo?

2021-07-07 06:56 UTC, curesh commented on src/components/InventoryManager/Sidebar/PriceMenu.js
> +  /* Sets checkboxes to checked/unchecked when toggled */
Remove comment if uneccessary

2021-07-07 06:59 UTC, curesh commented on src/components/Marketplace/MarketplaceScreen.js
> +// const airtableConfig = {
I think you can go ahead and delete these comments

2021-07-07 06:59 UTC, curesh commented on src/components/Marketplace/MarketplaceScreen.js
> +// const base = new Airtable({ apiKey: airtableConfig.apiKey }).base(airtableConfig.baseKey);
Delete this comment as well

2021-07-07 06:59 UTC, curesh commented on src/components/Marketplace/MarketplaceScreen.js
> +// import Airtable from 'airtable';
Also delete this comment

2021-07-07 07:03 UTC, curesh requested changes
Omg this was such a long feature and it was implemented so well :0 I am super super impressed! Your code is also really clean, and I barely had any comments to make on that end! I've included a few comments about the sorting feature and some edge cases, but otherwise it looks great. Thanks so much for your hard work

2021-07-18 06:11 UTC, hwang635 commented on src/components/InventoryManager/Sidebar/PriceMenu.js
> +const useStyles = makeStyles({
Could you make the min/max fonts a little smaller so that the entirety of max is visible?

2021-07-18 06:14 UTC, hwang635 commented on src/components/Marketplace/MarketplaceScreen.js
> +import { base } from '../../lib/airtable/airtable';
Could you remove one of the base imports, they're duplicated.

2021-07-18 06:17 UTC, hwang635 commented on src/components/InventoryManager/InventoryManagerScreen.js
>                  <DeleteButton deleteRecords={deleteSelectedRecords} />
The delete listing button kind of ends in an awkward place, could you edit the styling to move it to the left so the button endsapproximately where the background rectangle (surrounding the listing cards) underneath it ends?

2021-07-18 06:19 UTC, hwang635 requested changes
Hey Elwyn! Your changes are sound and the sidebar looks amazing. There are a couple small styling edits and then if you could fix the merge conflicts that would be great. Thanks so much for working on this!

2021-07-19 21:44 UTC, hwang635 approved these changes
Perfect, thanks so much for your work!

2021-07-19 23:46 UTC, curesh approved these changes

2021-07-20 18:35 UTC, merged